# Atelier Pandas

## Partie 1 – Series

### 1) Créer une Series contenant 4 températures

In [3]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/diamata/atelierPandas/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/diamata/atelierPandas/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
Using cached numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Installing collected packages: numpy, pandas
Successfully installed numpy-2.5.2 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import numpy as np

In [5]:
temperatures = pd.Series([22.5, 23.1, 21.8, 24.0])
temperatures

0    22.5
1    23.1
2    21.8
3    24.0
dtype: float64

### 2) Afficher son index

In [6]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

### 3) Afficher la 1ère valeur

In [7]:
temperatures.iloc[0]

np.float64(22.5)

### 4) Afficher la dernière valeur

In [8]:
temperatures.iloc[-1]

np.float64(24.0)

### 5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

#### Méthode 1 — en passant index directement :

In [9]:
temperatures_horaires = pd.Series([22.5, 23.1, 21.8, 24.0], index=["12h", "13h", "14h", "15h"])
temperatures_horaires

12h    22.5
13h    23.1
14h    21.8
15h    24.0
dtype: float64

#### Méthode 2 — à partir d'un dictionnaire :

In [10]:
temperatures_horaires = pd.Series({"12h": 22.5, "13h": 23.1, "14h": 21.8, "15h": 24.0})
temperatures_horaires

12h    22.5
13h    23.1
14h    21.8
15h    24.0
dtype: float64

### 6) Afficher la 1ère et la dernière valeur

In [11]:
premiere = temperatures_horaires.iloc[0]
derniere = temperatures_horaires.iloc[-1]
print(premiere, derniere)

22.5 24.0

## Partie 2 – DataFrame

### 1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant

In [12]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2) Importer le dataset mesures_capteurs.csv dans le dataframe df

In [13]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3) Afficher les dimensions de df

In [14]:
df.shape

(605, 9)